<?php
/*======================================================================+
 File name   : botton.inc
 Begin       : 2010-08-04
 Last Update : 2016-01-25

 Description : footer and copyright

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/
?>


  </tbody>
</table>

<!-- FOOTER -->
<footer class="bottom footer-container">

  <!-- Copyright -->
  <div class="footer-legal">
    <small>
      <p>Sinx for Association © 2011–2025 by Sergio Capretta</p>
      <p>
        Questo programma è fornito SENZA ALCUNA GARANZIA.<br>
        Si tratta di software libero e la sua ridistribuzione è libera, a determinate condizioni.<br>
        leggi <a target="_blank" href="http://www.gnu.org/licenses/gpl-3.0.html">GNU GPL v3</a> per i dettagli.
      </p>
      <p>

        Sinx è ufficialmente registrato su</br>
        <a target="_blank" href="http://savannah.nongnu.org/">Savannah</a></br>
        come software libero

      </p>
 <!--     <p>
        <a href="http://www.fsf.org" target="_blank">
          <img src="./Immagini/646150.png" alt="[FSF Associate Member]" />
        </a>
      </p>
-->    </small>
  </div>

</footer>
</body>
</body>
</html>
