<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lgencal = "January";
$Lfebcal = "February";
$Lmarcal = "March";
$Laprcal = "April";
$Lmagcal = "May";
$Lgiucal = "June";
$Lligcal = "July";
$Lagocal = "August";
$Lsetcal = "September";
$Lottcal = "October";
$Lnovcal = "November";
$Ldiccal = "Dicember";

$Lluncal = "Monday";
$Lmarcal = "Tuesday";
$Lmercal = "Wednesday";
$Lgiocal = "Thursday";
$Lvencal = "Friday";
$Lsabcal = "Saturday";
$Ldomcal = "Sunday";

$Ltitolocal2 = "Appointments calendar";
$Lsugg1cal2 = "It is possible to insert appointments by clicking on the preferred day<br>The days marked in orange already have an appointment registered";
$Lappoggical2 = "Today's appointments";
$Ldatacal2 = "Date";
$Ltitolo2cal2 = "Title";
$Ltestocal2 = "Text";
$Lnoeventical2 = "<h3>There are no registered events for today</h3>";
$Ltuttiappcal2 = "All registered appointments";
$Lsugg2cal2 = "It is possible to insert appointments by clicking on the preferred day.<br> The day with registered appointments will be yellow marked and it will be possible to add, modify or delete appointments.";
$Lliv1cal2 = "Your user has a level ";
$Lliv2cal2 = "Access to this area is only permitted to user ";
$Lliv3cal3 = "Admin";
?>
