<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

$Lpimmagine = "Image:";
$Listrimmagine = "Insert image or foto of the Associate [max size 30 KByte]";
$Lnomedaticomuni = "Name *:";
$Lcognomedaticomuni = "Surname :";
$Listrnome = "Associate Name";
$Listrcognome = "Associate Surname";
$Lindirizzo = "Address:";
$Listrindirizzo = "Ex.: Street Rome, 122/B";
$Lregione = "Region:";
$Lscegli = "Select...";
$Lprovincia = "District:";
$Lcomune = "Municipality:";
$Ltel = "Tel:";
$Listrtel = "No spaces or symbols";
$Lcell = "Cellphone:";
$Ldatanasc = "Birth date:";
$Listrdatan = "Ex.: gg-mm-aaaa";
$Lcodfiscale = "Tax Code:";
$Lassociato = "Associate:";
$Lassociatoattivo = " Active associate";
$Lnote = "Notes:";
$Lsuggregione = "Start typing region to speed up search";
$Lsuggprovincia = "Start typing district to speed up search";
$Lsuggcitta = "Start typing ZIP to speed up search";

?>
