<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ldatiassociazione= "Association Data";
$Linsomod = "Insert or modify all Association data";
$Llogoassociaz = "Association logo: ";
$Lnomeassociaz = "Association name:";
$Lvia = "Street:";
$Lnumero = "Number:";
$Lcap = "ZIP:";
$Lcitta = "City:";
$Lprovincia = "District:";
$Ltelefono = "Telephone:";
$Lfax = "Fax:";
$Lcfpi = "Tax Code and VAT:";
$Lindirizzo = "address ";
$Lsito = "Internet website:";
$Lcambialogo = "Change_logo";
$Linvia = "Sending";
$Lhelpdatiassociaz = "<hr><img src='./Immagini/suggerimento.png'><br><small><i>It is possible to modify association's data directly by pressing 'enter'.<br>To change the logo it is necessary to browse to 'images' folder of Sinx and change 'logo.png'. Be careful to maintain the same name plus extension and be sure to select an image with optimal size of 60px height<br><hr></i></small>";

?>
