<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloemail = "Send e-mail";
$Laemail = "TO";
$Ldestinatarioemail = "Select recipient";
$Ltuttiemail = "All associates";
$Lesclusicollabemail = "Only coop and external collaborators excluded";
$Lfondatoriemail = "Only administrative charges";
$Llistafondatoriemail = "President, councillors and administrators list";
$Loggemail = "Object";
$Lmessgemail = "Message";
$Lsugg1email = "It is possible to use html tags to create the message ex.: ";
$Lacapoemail = "wraps";
$Lgrassettoemail = "Bold";
$Lcorsivoemail = "Italic";
$Lorizzemail = "Horizontal line";
$Lpuntatoemail = "Bulleted list ";
$Ltitoliemail = "Titles";
$Lsalvaemail = "Save e-mail";
$Lnota1email = "*** All fields marked with an asterisk are mandatory! ***";
$Lnota2email = "You can select if:<li>Send a non registered mail by manually compiling it</li><li>Send a mail tu an associate</li><li>Send a mail to all associates</li><li>Send a mail only to founders</li><br>Be careful that some provider block massive mails marking them as spam";

?>
