<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitologestfiles = "Loading images and files";
$Lcaricaimmagine = "Load Image";
$Lsugg1caricaimmagine = "Insert image or picture of the associate <b>max 30 kByte";
$Lsugg2caricaimmagine = "In this form you can insert ad-hoc images for associate fields.<br>The images can be of gif, jpg, png formats but <b>can't outrange 30KByte</b>.<br>Once uploaded you must assign the image to the Associate by using the <b>'Modify'</b> function in the associate's record.";
$Ltitolocaricamoduli = "Loading New Modules";
$Lcaricafile = "File Upload:";
$Lsugg1caricafiles = "General modules and files upload <b>max 1 MByte</b> in pdf,txt format";
$Lsugg2caricafiles = "Upload box for precompiled modules; It is possible to upload pdf, or txt files which <b>do not exceed 1MByte</b>";
$Lfileeimmaginicaricate = "Uploaded File and Images";
$Lcaricamentologo = "Loading association logo";
$Lcaricalogo = "Upload Association logo:";
$Lsugg2caricalogo = "Insert Association logo <b>max 30 kByte</b>";
$Lsugg1caricalogo = "The image will be renamed into: logo.png; optimal dimensions are 60px height and its dimension cannot exceed 30Kb;<br>The logo is inside 'Images' folder of Sinx";
$Lhelpgestimmagini = "Here you can insert Associates' images but also useful pdf files for the Association.<br>Read carefully bottom page notes.<br>If files are not correctly uploaded check 'Download' and 'Immagini/Utenti' folder permissions";
$Llivello1gestimmagini = "Your user has a level ";
$Llivello2gestimmagini = "This area is permitted exclusively to user ";

?>
