<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitologestfiles = "Caricamento immagini e files";
$Lcaricaimmagine = "Carica Immagine";
$Lsugg1caricaimmagine = "Inserisci l'immagine o foto dell'Associato <b>massimo 30 kByte";
$Lsugg2caricaimmagine = "In questa casella si inseriscono le immagini dedicate per le schede associati.<br>Le immagini possono essere di tipo gif, jpg, png, ma <b>non possono superare i 30Kbyte</b>.<br>Una volta caricata l'immagine bisogna assegnarla all'Associato utilizzando la funzione <b>'Modifica'</b> presente nella scheda associato.";
$Ltitolocaricamoduli = "Caricamento Nuovi Moduli";
$Lcaricafile = "Carica File:";
$Lsugg1caricafiles = "Upload di moduli e files in generale <b>massimo 1 MByte</b> del tipo pdf,txt";
$Lsugg2caricafiles = "Casella dedicata all'upload dei moduli precompilati; &egrave possibile caricare file di tipo pdf, o txt che <b>non superino 1Mbyte";
$Lfileeimmaginicaricate = "File e Immagini caricate";
$Lcaricamentologo = "Caricamento logo Associazione";
$Lcaricalogo = "Carica Logo Associazione:";
$Lsugg2caricalogo = "Inserisci il logo dell'Associazione <b>massimo 30 kByte";
$Lsugg1caricalogo = "L'mmagine verr&agrave rinominata: logo.png; le dimensioni ottimali sono di 60px di altezza e non pu&ograve superare i 30Kb;<br>Il logo risiede nella cartella 'Immagini' di Sinx";
$Lhelpgestimmagini = "Da qui puoi inserire le immagini degli associati, ma anche i file pdf che ritieni utili alla tua associazione.<br>Leggi attentamente le note nella pagina.<br>Se i file non si caricano, verifica i permessi nelle cartelle 'Download' e 'Immagini/Utenti'";
$Llivello1gestimmagini = "Il tuo utente ha un livello ";
$Llivello2gestimmagini = "Area permessa solo all'utente ";

?>