<?php
/*======================================================================+
 File name   : IMPORTACSV.inc
 Begin       : 2014-02-02
 Last Update : 2014-02-02

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$LTitoloimportacsv = "Loading demographic csv file";
$Lcaricafile = "File upload";
$Lsugg1caricafiles = "File must have csv extension, fields must be ; separated";
$Lsugg2caricafiles = "If you already have names in the demographic section, these will NOT be deleted; The import process adds name in tail, the card numbering is automatic";


?>
