<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//Menu
$Lassociazione = "Association";
$Lsito = " Website";
$Ldatiassociazione = " Association data";
$Lanagrafica = "Demographic";
$Lfondatori = " Founders";
$Lassociati = " Associated";
$Laltri = " Others";
$Lcerca = " Search";
$Lrubrica = " Address Book";
$Llibrosoci = " Shareholders";


//top
$Lpresentazione = "Management tool for non-profit Associations";
$Lutente = "User: ";
$Llivello = "Level: ";
$Lora = "Hour: ";
$Ldata = "Date: ";
$Lversione = "Version: ";

//index2
$Lbenvenuto = "Welcome";
$Lfrase = "Welcome on Sinx: management software for non-profit Associations.<br>Sinx is freely available under <a href='./Licenza.php'>GPLv3 license (GNU General Public License)</a><br>
<a href='./Licenza_eng.php'>Official license version GPLv3</a><br><br>
This software comes with NO WARRANTIES.<br><br>
If you have suggestions or you feel like contributing to the development have a look at <a href='http://www.sinx.it'>http://www.sinx.it</a> (Italian website) or send an email to <a href='mailto:info@sinx.it'>info@sinx.it</a>.<br><br>
<center><img style='border: 0px; width: 30px; height: 30px;' src='./ImmTemplate/logoFirefox.jpg'><br><small><b>This website is optimized for Mozilla Firefox</b></small>
<p><center>To administer the system, clic on one of the left menu links.<br>If you didn't do it already, <b>take a look at Sinx manual</b>, you can find it also in the menu</p><br><br>
Enjoy your work!";

//help
$Lhelpindex2 = "<hr><img src='./Immagini/suggerimento.png'><small><i>First three letters of the menu inform user about access permissions on pages:<br>A - admin<br>o - operator<br>l - limited<br>a - associate<br><br>x - You can not enter<br>- - You can enter but do not change<br><hr></i></small>";
?>
