<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lpresentazioneextra = "Extra demographic and employees";
$Lnotaextra = "Fields marked with an asterisk are mandatory";
$Lmansione = "Task and/or function:";
$Linvia = "Sending";
$Lhelpextra = "<hr><img src='./Immagini/suggerimento.png'><small><i>Here it is possible to insert external collaborators demographic.<br>They can be consultants, occasional collaborators or professionals that give hints for a project.<br>Optionally it is possible to subscribe them as associates as well using the 'Active associate' checkbox'
<hr></i></small>";

?>
