<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitolocontoec = "Income statement";
$Lnota1 = "Fields marked with an asterisk are mandatory";
$Lstampacontoec = "Print income statement";
$Lazzeracontoec = "Reset income statement";
$Lcancella = "Delete";
$Lnota2 = "Insert ID to delete and select delete";
$Lnumero = "Number";
$Lmodifica = "Modify";
$Lnota3 = "Insert ID and the field to modify<br>Insert the modification on New record and select modify";
$Lcampo = "Field";
$Ldescrizione = "Description";
$Lvalore = "Value";
$Lnuovorecord = "New record";
$Lnuovavocecontoec = "New invoice income statement";
$Loperazione = "Operation";
$Linscausale = "Insert causal";
$Lnota4 = "Avoid using symbols like +,-,* etc. Decimals must be written with a dotted notation ex.: 123.45";
$Ltipovoce = "Invoice type";
$Lproventiric = "Income and Revenues";
$Lcostioneri = "Costs and charges";
$Lid = "ID";
$Limporto = "Import";
$Ltotproventi = "Income total";
$Ltotspese = "Totale Expenses";
$Lavanzogestione = "Operating surplus";
$Ltotpareggio = "Total draw";
$Lhelpcontoec = "Economical account is automatically managed by Sinx which already has some major items.<br>However you can add items from here and, if it is necessary you can modify existent items and values.<br>If you reset the income statement you must manually restore values.";

?>
