<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lptitolofattura = "Invoicing";
$Lstampa = "Invoice print";
$Lnumerofattura = "Invoice number";
$Lregistrafattura = "Record invoice ";
$Lvocecontoec = "Income statement item";
$Lcausale = "Causal";
$Linscausale = "Insert causal";
$Lincassoin = "Income in";
$Lcassa = "Cash";
$Lbanca = "Bank";
$Lcompfattura = "Complete invoice";
$Lnota1 = "Fields marked with an asterisk are mandatory";
$Lnomecliente = "Client name";
$Ldata = "Date";
$Ldescrizione = "Description";
$Lquantita = "Quantity";
$Lprezzoun = "Pricy a";
$Liva = "VAT %";
$Lnota2 = "To insert multiple items inside a single invoice, it is possible to insert the same invoice number, the program will insert in queue the item and will automatically calculate the total";
$Lvisualizzafatt = "View invoices";
$Lnota3 = "Here you can view and modify single invoice details and modify";
$Lelencofatture = "Invoices list";
$Ltotivaincl = "Total including VATs";
$L_stampafattura = "-Invoice-print-";
$Lhelpfatture = "When emitting an invoice, this will not be registered in accountancy until it will be registered with 'Record invoice'.<br>In this way you can decide whethet to register invoices in the issueing or in the taking.";

?>
