<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloprimanota = "First cash bill registry";
$Lnota = "Fields marked with an asterisk are mandatory";
$Lstampa = "Print petty cash";
$Lazzera = "Reset petty cash";
$Lcancella = "Delete";
$Linserisciid = "Insert ID to delete and select delete";
$Lmodifica = "Modify";
$Linserisciidmodifica = "Insert id number and field to modify <br>Insert modify on New record and press modify";
$Lnumero = "Number";
$Lcampo = "Field";
$Ldata = "Date";
$Ldescrizione = "Description";
$Lentratacassa = "Incoming Cash";
$Luscitacassa = "Outgoing Cash";
$Lentratabanca = "Bank entry";
$Luscitabanca = "Bank output";
$Lnuovorecord = "New record";
$Lnuovomovimento = "New petty cash movement";
$Lvocecontoec = "Account item ec.*:";
$Lcausale = "Causal";
$Linserirecausale = "Insert causal";
$Loperazione = "Operation*:";
$Linserirecausale = "Insert movement causal";
$Limporto = "Amount:";
$Lsuggdecimali = "To represent decimal use dotted notation ex.: 123.45";
$Ltipodivoce = "Item type:";
$Ltipomovimento = "Movement type:";
$Lcassa = "Cash";
$Lentrata = "Entry";
$Luscita = "Outgo";
$Lbanca = "Bank";
$Lprimanota = "Petty cash";
$Lguadperdita = "Guad/Loss";
$Lhelpprimanota = "When emitting a receipt or an invoice, these will be automatically registered in petty cash.<br>Here you can register new cash outflows or bank and other incoming types.";

?>
