<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2014-01-19

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloric = "Receipt";
$Lnotaric = "Fields in red are required";
$Lstampa = "Print";
$Listrstampa = "Enter the receipt number and press -Print-";
$Lnumero = "Number";
$Lcancella = "Clears";
$Listrcancella = "Enter the receipt number and press -Clears-";
$Lnumric = "Receipt number";
$Lvocecontoec = "Income statement item";
$Lcausale = "Causal";
$Listrcontoec = "Indica dove &egrave inserita la voce nel conto economico per poterla scalare";
$Lmodifica = "Modification";
$Listrmodifica = "Inserisci in numero della ricevuta e campo da modificare<br>Inserisci la modifica su Nuovo record e premi modifica";
$Lcampo = "Field";
$Lnome = "Name";
$Ldata = "Date";
$Lmodalita = "Modality";
$Lsuggcausale = "Choose mode, if free fill out the field";
$Lpreimpostata = " Preset";
$Llibera = " Free";
$Lprezzo = "Price";
$Ldescrizione = "Description";
$Ltesseramentocscadenza = "Membership with a maturity notice to 12 mounths";
$Ltesseramentonoscadenza = "Membership without notice";
$Lnuovorecord = "New record";
$Listrnuovorecord = "If you change a price, remember to also update the income statement";
$Lnuova = "New";
$Linserirecausale = "Insert the causative";
$Lricevutoda = "<small>Received from</small>";
$Leuro = "Euro";
$Lstampcancmod = "Print | Clears | Modify";
$Linvia = "Send";
$Lelencoricevute = "List receipts";
$Lhelpric = "The receipt number is automatic, the date is preset but you can change.<br>Remember to always include correctly the income statement item to keep an accurate accounting.";

?>
