<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2014-01-19

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloric = "Receipt";
$Lnotaric = "Fields marked with an asterisk are mandatory";
$Lstampa = "Print";
$Listrstampa = "Insert receipt number and select -Print-";
$Lnumero = "Number";
$Lcancella = "Delete";
$Listrcancella = "Insert receipt number to delete and select delete";
$Lnumric = "Receipt number";
$Lvocecontoec = "Account voice ec.";
$Lcausale = "Causal";
$Listrcontoec = "State where the income statement voice is inserted so that it will be possible to scale it";
$Lmodifica = "Modify";
$Listrmodifica = "Inserte receipt number and field to modify<br>Insert modification on a New record and select modify";
$Lcampo = "Field";
$Lnome = "Name";
$Ldata = "Date";
$Lmodalita = "Modality ";
$Lsuggcausale = "Select modality, if empty fill the form below";
$Lpreimpostata = " Preset ";
$Llibera = " Free";
$Lprezzo = "Price";
$Ldescrizione = "Description";
$Ltesseramentocscadenza = "Membership with 12 months expiry notify";
$Ltesseramentonoscadenza = "Membership without expiry notify";
$Lnuovorecord = "New record";
$Listrnuovorecord = "If a price is modified, update income statement";
$Lnuova = "New";
$Linserirecausale = "Insert causal";
$Lricevutoda = "<small>Received from</small>";
$Leuro = "Euro";
$Lelencoricevute = "List receipts";
$Lhelpric = "Progressive receipt number is automatic, whilst date is preset, but you can modify it.<br>Remember to always insert correctly the income statement voice to maintain an exact accounting.";

?>