<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitolostatopatr = "Balance sheet";
$Lnota1 = "Fields marked with an asterisk are mandatory";
$Lstampastatopat = "Print Balance sheet";
$Lazzerastatopat = "Reset Balance sheet";
$Lcancella = "Delete";
$Lnotacancella = "Insert ID number to delete and select delete";
$Lnumero = "Number";
$Lmodifica = "Modify";
$Lnotamodifica = "Insert ID number and field to modify<br>Insert modification on New record and select modify";
$Lcampo = "Field";
$Ldescrizione = "Description";
$Lvalore = "Value";
$Lnuovorecord = "New record";
$Lnuovavoce = "New Balance sheet voice";
$Loperazione = "Operation";
$Linscausale = "Insert causal";
$Lnotavalore = "Avoid inserting symbols like +,-* etc. decimals must be inserted with a dotted notation such as: 123.45";
$Ltipovoce = "Voice type";
$Lattivita = "Activity";
$Lpassivita = "Passivity";
$Lid = "ID";
$Limporto = "Import";
$Ltotaleattivi = "Active total";
$Ltotalepassivi = "Passiv total";
$Lavanzogestione = "Operating surplus";
$Ltotpareggio = "Total draw";
$Lhelpatatopatr = "Sinx automatically assigns cash and bank amounts in the balance sheet.<br>Other Association assets can be inserted by selecting 'modify' and assigning the field 'value' and the reference entry ID.<br>Sinx will recalculate totals.<br>It is always possible to delete, modify and add more assets voices.";
?>