<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloutente = "Gestione Utenti";
$Lcancutente = "Cancella";
$Lsuggcancutente = "Inserisci il numero id da <b>cancellare</b> e premi cancella";
$Lmodutente = "Modifica";
$Lsuggmodutente = "Inserisci in numero id<br>Inserisci la <b>modifica</b> su Nuovo record e premi modifica";
$Lcampoutente = "Campo";
$Lsuggcampoutente = "Seleziona il campo da modificare";
$Lnomeutente = "Nome Utente";
$Llivelloutente = "livello";
$Lnuovorecordutente = "Nuovo record";
$Linsnuovoutente = "Inserimento nuovo utente";
$Lsuggnuovoutente = "I campi contrassegnati con l'asterisco sono obbligatori";
$Lnuovoutente = "Nome Utente";
$Lamministrutente = "Amministratore";
$Llimitatoutente = "Utilizzatore limitato";
$Loperatoreutente = "Operatore";
$Lpasswdutente = "Password";
$Lutenteutente = "Utente";
$Lhelputente = "Puoi inserire quanti utenti vuoi e modificarne anche successivamente il livello di accesso.<br>Non puoi modificare la password degli utenti, ma, se serve, puoi creare un utente con lo stesso nome ed una password diversa.";
$Lsugg1utente = "Il tuo utente ha un livello ";
$Lsugg2utente = "Area permessa solo all'utente ";

?>