<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//Menu
$Lassociazione = "Association";
$Lsito = " Web site";
$Ldatiassociazione = " Data Association";
$Lmail="Web Mail";
$Lmailpec="Web Mail Pec";
$Lfacebook="Facebook";
$Linstagram="Instagram";
$Lyoutube="YouTube";
$Ltwitter="Twitter";
$LHomeBanking="Home Banking";
$Lanagrafica = " Registry";
$Lfondatori = " Charges Amminstr";
$Lassociati = " Associates";
$Limporta = " Import from csv";
$Laltri = " Other/Staff";
$Lcerca = " Search";
$Lrubrica = " Address book";
$Llibrosoci = " Register of Members";
$Lcontabilita = "Accounting";
$Lprimanota = " First note";
$Lquietanza = " Receipt";
$Lfattura = " Invoice";
$Lcontoec = " Income Statement";
$Lstatopat = " Balance Sheet";
$Lrendiconto = " Report";
$Lnuovoannosociale = " New Year Social";
$Lgestione = "Management";
$Lmoduli = " Modules";
$Lcalendario = " Calendar";
$Lutenti = " Users";
$Lfileseimmagini = " Files and Immages";
$Llog = " System Log";
$Lspecifiche = "Specifications";
$Lfunzioniassociati = " Associated functions";
$Ltipoassociati = " Type Associates";
$Lmanuale = "Manual";
$Luscita = "Exit";
$Llicenza = "Gnu GpL/v3 license";
$Lblocconote = "Block Notes";

?>
