<?php
/*======================================================================+
 File name   : moduli.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitolomoduli = "Inserisci i dati richiesti";
$Lsugg1moduli = "Sotto le caselle sono indicati i moduli di riferimento";
$Lmodulo = "Modulo";
$Lammissionsocio = "Richiesta ammissione a Socio ";
$Lammissionesociominore = "Richiesta ammissione Socio minore ";
$Lconsensoprivacy = "Consenso Privacy ";
$Ldimissionisocio = "Dimissioni Socio ";
$Lverbassemblea = "Verbale Assemblea";
$Lverbale = "Verbale";
$Lriunione= "riunione ";
$Lconvocazioneconsiglio = "Convocazione Consiglio Direttivo ";
$Lrimborsospese = "Richiesta rimborso spese ";
$Lassociato = "Associato";
$Lnome = "Nome";
$Ldata = "Data";
$Ltuttimoduli = "per tutti i moduli";
$Lsugg2moduli = "E' possibile utilizzare i tag html es.:";
$Lvacapo = "va a capo";
$Lgrassetto = "Grassetto";
$Lcorsivo = "Corsivo";
$Llineaorr = "Linea orizzontale";
$Lelenco = "elenco puntato";
$Lsocipresenti = "Soci Presenti";
$Lsocio = "Socio";
$Lordinegiorno = "Ordine del giorno";
$Luno = " Uno";
$Ldue = " Due";
$Lsugg3moduli = "Puoi preparare un modulo utilizzando il form qui a fianco, oppure, premendo il pulsante in basso 'files e immagini' puoi utilizzare i moduli in pdf.";
$Llivutente1 = "Il tuo utente ha un livello ";
$Llivutente2 = "Area permessa solo all'utente ";
$Llivutente3 = "Admin";
$Lrapportosoci = "Rapporto attivit&agrave soci";
$Lluogoattivitasoci = "Luogo attivit&agrave soci";
$Lconvocazioneassemblea = "Convocazione Assemblea ordinaria o straordinaria ";
$Ldataritrovo = "Prima convocazione Assemblea";
$Ldataritrovo2 = "Seconda convocazione Assemblea";
$Ldata2 = "Data e Ora";
$Ldata3 = "Data e Ora";

?>