<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$LtitoloNannosoc = "Nuovo anno sociale";
$LattenzioneNannosoc = "ATTENZIONE";
$LavvertenzaNannosoc = "!!! Premendo il pulsante azzera, si cancelleranno tutti i dati contabili !!!";
$LannullaesciNannosoc = "Annulla/Esci";
$LmsarchiviaNannosoc = "Premendo 'Archivia' otterrai un resoconto di tutti i dati registrati pronto per essere salvato o stampato.";

$Lmslogin1Nannosoc = "Il tuo utente ha un livello ";
$Lmslogin2Nannosoc = "Area permessa solo all'utente ";
$Lmslogin3Nannosoc = "Admin";

?>