<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloricerca = "Research associates";
$Lfondatori = "Executive";
$Lfunzione = "Function";
$Lnota1 = "leaving free, you will get the complete linst in alphabetical order";
$Lassociati = " Associated";
$Ltipo = "Tipe";
$Lcontatti = " Contacts";
$Lricercaricevute = "Research receipts associated";
$Lnota2 = "This function performs a search within the receipts issued.<br>
Useful to view the list of members, or those who have made contributions.<br>
You can enter more words in the same search by entering the <b>special character % </b>between them.<br>
Research not is case sensitive";
$Lcamporicerca = "Research field:";
$Lricercanome = " name |";
$Lricercadescrizione = " description |";
$Lvalore = " value |";
$Lricercadata = " date";
$Lricerca = "Research *:";
$Lcerca = "Serch";
$Ltitoloesempio = "eg use special character %:";
$Lesempioricric = "<small><b>%descr% - </b>Look all that includes 'descr' including what is before and after</small><br>
<small><b>Rob% - </b>Search all words satrting with Rob and what's next</small><br>
<small><b>%2016 - </b>Look for all the dates of the year 2016</small>";
$Lhelpricerca = "<hr><img src='./Immagini/suggerimento.png'><small><i>Nella ricerca per nome &egrave possibile ottenere la lista completa in ordine alfabetico non selezionando le lettere di ricerca.<br>La ricerca ricevute &egrave utile per avere la lista dei tesserati o le ricevute emesse per un progetto o in un determinato periodo di tempo.
<hr></i></small>";

?>
