<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2016-08-17
 Last Update : 2016-08-17

 Description : english language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

$Lelencosoci = "List members";
$Lntessera = "N. Card";
$Lnome = "Name";
$Lindirizzo = "Address";
$LCitta = "City";
$LProvincia = "Provincie";
$Lemail = "e-mail";
$LFunzTipo = "Function/Tipe";
$LAttivo = "Active";
$Lnota = "To display the associated tab, push the button id next to aech name";

?>
