<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lpresentazionebackup = "Backup data management";
$Lbackup = "Data Backup";
$Lcomandobackup = "Press the button to save data";
$Lripristino = "Restoring data";
$Listrripristino = "Section to restore previously saved data<br><b>Caution!!</b> you may be able to restore the data we want a moment, wait during recovery without interrupting";
$Lfilebackup = "File Backup:";
$Lhelpbackup = "<hr><img src='./Immagini/suggerimento.png'><small><i>It 'always advisable to make a backup of data periodically.<br>The backup file is saved to the local PC and not on the server
<hr></i></small>";
$Lutentelimitato = "<center>Your user level<b>$user</b> <br>Area permitted only to the user <b>Admin</b></center>";
$Linvia = "Sending";

?>
