<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lgencal = "Gennaio";
$Lfebcal = "Febbraio";
$Lmarzcal = "Marzo";
$Laprcal = "Aprile";
$Lmagcal = "Maggio";
$Lgiucal = "Giugno";
$Lligcal = "Luglio";
$Lagocal = "Agosto";
$Lsetcal = "Settembre";
$Lottcal = "Ottobre";
$Lnovcal = "Novembre";
$Ldiccal = "Dicembre";

$Lluncal = "Luned&igrave";
$Lmarcal = "Marted&igrave";
$Lmercal = "Mercoled&igrave";
$Lgiocal = "Gioved&igrave";
$Lvencal = "Venerd&igrave";
$Lsabcal = "Sabato";
$Ldomcal = "Domenica";

$Ltitolocal2 = "Calendario appuntamenti";
$Lsugg1cal2 = "E' possibile inserire gli appuntamenti cliccando sul giorno desiderato<br>I giorni evidenziati hanno un appuntamento registrato";
$Lappoggical2 = "Appuntamenti di oggi";
$Ldatacal2 = "Data";
$Ltitolo2cal2 = "Titolo";
$Ltestocal2 = "Testo";
$Lnoeventical2 = "<h3>Non ci sono eventi registrati per oggi</h3>";
$Ltuttiappcal2 = "Tutti gli appuntamenti registrati";
$Lsugg2cal2 = "Puoi inserire un nuovo appuntamento cliccando sopra al giorno del calendario.<br>Il giorno con degli appuntamenti registrati diventer&agrave evidenziato e potrai aggiungere, modificare o cancellare appuntamenti.";

$Lliv1cal2 = "Il tuo utente ha un livello ";
$Lliv2cal2 = "Area permessa solo all'utente ";
$Lliv3cal3 = "Admin";
?>
