<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ldatiassociazione= "Dati dell'Associazione";
$Linsomod = "Inserisci o modifica tutti i dati dell'Associazione";
$Llogoassociaz = "Logo Associazione: ";
$Lnomeassociaz = "Nome Associazione:";
$Lvia = "Via:";
$Lnumero = "Numero:";
$Lcap = "CAP:";
$Lcitta = "Citt&agrave:";
$Lprovincia = "Provincia:";
$Ltelefono = "Telefono:";
$Lfax = "Fax:";
$Lcfpi = "Codice Fiscale ed eventuale Partita Iva:";
$Lindirizzo = "indirizzo ";
$LPEC = "PEC ";
$LwebPEC = "webPEC ";
$Lsito = "sito internet:";
$Lfacebook = "Facebook ";
$Linstagram = "Instagram ";
$Ltwitter = "Twitter ";
$Lyoutube = "YouTube ";
$Lbanca = "Banca ";
$LIBAN = "IBAN ";
$LBIC = "BIC ";
$LHomeBanking = "Home Banking ";
$LIscrizioneODVoAPS = "N.Iscrizione APS o ODV ";
$Lcambialogo = "Cambia_logo";
$Linvia = "Invia";
$Lhelpdatiassociaz = "<hr><center><img src='./Immagini/suggerimento.png'><br><small><i>L'amministratore pu&ograve modificare i dati dell'associazione da qui, correggendo e premendo 'invia'.<br><hr></i></small></center>";

?>
