<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloemail = "Spedizione e-mail";
$Laemail = "A";
$Ldestinatarioemail = "Seleziona destinatario";
$Ltuttiemail = "Tutti gli associati";
$Lesclusicollabemail = "Sono esclusi solo i collaboratori ed esterni";
$Lfondatoriemail = "Solo Cariche Direttive";
$Llistafondatoriemail = "Presidente, consiglieri e la lista del direttivo";
$Loggemail = "Oggetto";
$Lmessgemail = "Messaggio";
$Lsugg1email = "E' possibile utilizzare i tag html per creare il messaggio es.: ";
$Lacapoemail = "va a capo";
$Lgrassettoemail = "Grassetto";
$Lcorsivoemail = "Corsivo";
$Lorizzemail = "Linea orizzontale";
$Lpuntatoemail = "elenco puntato";
$Ltitoliemail = "Titoli";
$Lsalvaemail = "Salva Mail";
$Lnota1email = "*** Tutti i campi contrassegnati con l'asterisco, sono obbligatori! ***";
$Lnota2email = "Puoi selezionare se:<li>Spedire una mail non registrata compilandola manualmente</li><li>Spedire una mail ad un associato</li><li>Spedire una mail a tutti gli associati</li><li>Spedire una mail a solo i fondatori</li><br>Fai attenzione che certi provider bloccano le mail di massa ritenendole spam";


?>
