<?php
/*======================================================================+
 File name   : NFile.inc
 Begin       : 2016-08-13
 Last Update : 2016-08-13

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitologestfiles = "Moduli e files caricati";
$Lcaricaimmagine = "Immagini caricate";

$Lhelpgestimmagini = "<hr><img src='./Immagini/suggerimento.png'><small><i>Questa pagina elenca le cartelle, file e immagini; i file sono presenti nella cartella ./Download di Sinx, le immagini in ./Immagini/Utenti.<br> puoi aggiungere cartelle e file direttamente all'interno della cartella Download, Sinx le elencher&agrave in automatico<br><br>Se carichi i file da Sinx, di default verranno inseriti nella cartella Download; potrai cambiare la posizione in qualsiasi momento.<hr></i></small>";
$Llivello1gestimmagini = "<center>Il tuo utente ha un livello <b>$user</b> <br>Area permessa solo all'utente <b>Admin</b></center>";


?>
