<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//Menu
$Lassociazione = "Associazione";
$Lsito = " Sito Web";
$Ldatiassociazione = " Dati Associazione";
$Lanagrafica = "Anagrafica";
$Lfondatori = " Fondatori";
$Lassociati = " Associati";
$Laltri = " Altri";
$Lcerca = " Cerca";
$Lrubrica = " Rubrica";
$Llibrosoci = " Libro Soci";


//top
$Lpresentazione = "Gestionale per Associazioni senza scopo di lucro";
$Lutente = "Utente: ";
$Llivello = "Livello: ";
$Lora = "Ora: ";
$Ldata = "Data: ";
$Lversione = "Versione: ";

//index2
$Lbenvenuto = "Benvenuto";
$Lfrase = "Benvenuti in Sinx: sofware gestionale pensato per Associazioni No-Profit.<br>
Sinx &egrave liberamente disponibile sotto <a href='./Licenza.php'>licenza GPLv3 (GNU General Public License)</a><br>
<a href='./Licenza_eng.php'>Versione ufficiale licenza GPLv3</a><br><br>
Questo software NON HA ALCUNA GARANZIA.<br><br>
Se hai dei suggerimenti o vuoi partecipare pi&ugrave o meno attivamente allo sviluppo del software, se vuoi dare un contributo o essere aggiornato con tutte le novit&agrave di Sinx, inviami una mail a <a href='mailto:sinxsoftware@protonmail.com'>QUI</a>.<br><br>
<p><center>Per amministrare il sistema, fare clic su uno dei link nel menu alla sinistra dello schermo.<br>Se non lo hai gi&agrave fatto, <b>leggi bene il manuale d'uso di Sinx</b>, lo trovi anche nel men&ugrave</p>";
$Lptitolonote = "<a href='./InsNotepad.php'>Blocco Note</a>";
$Ldescrizionenote = "<a href='./InsNotepad.php'>Da qui</a> o da men&ugrave (Gestione -> Blocco Note), puoi gestire le note";
$Ldonazione= "Il lavoro e il tempo per la realizzazione di questo programma sono tanti, puoi sostenere questo progetto con una semplice donazione";

//help
$Lhelpindex2 = "<hr><img src='./Immagini/suggerimento.png'><small><i>Sinx ha diversi livelli di permessi. Alcune voci sono limitate ai soli amministratori. Verifica sulla barra in alto, nel centro, che livello di autorizzazione hai<br><hr></i></small>";
$LlinkDaHome = "Per modificare le note vai sul "
?>
