<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lpresentazioneanagrstud = "Inserimento dati anagrafici del direttivo</h2><small>I campi contrassegnati con l'asterisco sono obbligatori";
$Lfunzione = "Funzione ";
$Ltessere = "Vedi Tessere registrate";
$Lntessera = "Numero di Tessera";
$Linvia = "Invia";
$Listntessera = "Numero di Tessera o identificativo nel caso di non soci";
$Lhelpanagrstud = "<hr><img src='./Immagini/suggerimento.png'><small><i>Quasi tutti i campi sono facoltativi anche se &egrave consigliabile inserire pi&ugrave informazioni possibili.<br>E' possibile inserire la foto dell'associato e selezionare da subito se &egrave socio attivo oppure no.<br/><br/>In ogni momento &egrave possibile cambiare le cariche direttive tramite le schede associati.
<hr></i></small>";

?>
