<?php
/*======================================================================+
 File name   : IMPORTACSV.inc
 Begin       : 2014-02-02
 Last Update : 2017-12-08

 Description : italy language file

 Author: Marco Pedrazzi

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$LTitoloimportacsv = "Importazione anagrafica da file";
$Lcaricafile = "Upload del file";
$Lsugg1caricafiles = "Il file dovr&agrave essere in formato CSV (estensione .csv).</br>
<p>E' possibile scaricare il template del file <a href='DocTemplate/Template_anagrafica.csv' download>cliccando sul link</a>. </p></br>
I campi con <strong>'*' sono obbligatori</strong>, mentre &egrave richiesto <strong>solo uno dei seguenti campi: <font color='blue'> materia | classe | mansione </font></strong>";
$Lsugg2caricafiles = "<br>Se hai gi&agrave dei nominativi in anagrafica, questi NON vengono cancellati, l'importazione aggiunge i nomi in coda.";
$LNota = "<li>materia = tipo di socio</li><li>classe = funzione dell'associato</li><li>mansione = funzione dei collaboratori</li>";
?>
