<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitolocontoec = "Conto Economico";
$Lnota1 = "I campi contrassegnati con l'asterisco sono obbligatori";
$Lstampacontoec = "Stampa Conto economico";
$Lazzeracontoec = "Azzera Conto economico";
$Lcancella = "Cancella";
$Lnota2 = "Inserisci il numero id da cancellare e premi cancella";
$Lnumero = "Numero";
$Lmodifica = "Modifica";
$Lnota3 = "Inserisci in numero id e campo da modificare<br>Inserisci la modifica su Nuovo record e premi modifica";
$Lcampo = "Campo";
$Ldescrizione = "Descrizione";
$Lvalore = "Valore";
$Lnuovorecord = "Nuovo record";
$Lnuovavocecontoec = "Nuova voce conto economico";
$Loperazione = "Operazione";
$Linscausale = "Inserire la causale";
$Lnota4 = "Evitare di inserire simboli come +,-* ecc. i decimali vanno con il punto es.: 123.45";
$Ltipovoce = "Tipo di voce";
$Lproventiric = "Proventi e Ricavi";
$Lcostioneri = "Costi e Oneri";
$Lid = "id";
$Limporto = "Importo";
$Ltotproventi = "Totale Proventi";
$Ltotspese = "Totale Spese";
$Lavanzogestione = "Avanzo di Gestione";
$Ltotpareggio = "Totale a pareggio";
$Lhelpcontoec = "Il conto economico viene gestito automaticamente da Sinx che gi&agrave dispone delle voci principali.<br>Puoi comunque da qui aggiungere voci e, se serve modificare quelle esistenti o anche i valori.<br>Se azzeri il conto economico, dovrai ripristinare le valute manualmente.";

?>