<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lptitolofattura = "Emissione Fatture";
$Lstampa = "Stampa Fattura";
$Lnumerofattura = "Numero Fattura";
$Lregistrafattura = "Registra incasso Fattura";
$Lvocecontoec = "Voce Conto economico";
$Lcausale = "Causale";
$Linscausale = "Inserire la causale";
$Lincassoin = "Incasso in";
$Lcassa = "Cassa";
$Lbanca = "Banca";
$Lcompfattura = "Compilazione fattura";
$Lnota1 = "I campi contrassegnati con l'asterisco sono obbligatori";
$Lnomecliente = "Nome Cliente";
$Ldata = "Data";
$Ldescrizione = "Descrizione";
$Lquantita = "Quantit&agrave";
$Lprezzoun = "Prezzo un";
$Liva = "Iva %";
$Lmodpaga = "Modalita di pagamento";
$Lnota2 = "Per inserire pi&ugrave voci nella stessa fattura, basta inserire lo stesso numero di fattura, il programma inserir&agrave in coda la voce e calcoler&agrave automaticamente il totale";
$Lvisualizzafatt = "Visualizzazione Fatture";
$Lnota3 = "Da qui &egrave possibile visualizzare i dettagli per singola fattura e modificare";
$Lelencofatture = "Elenco Fatture";
$Ltotivaincl = "Tot Iva inclusa";
$L_stampafattura = "-Stampa-Fattura-";
$Lhelpfatture = "Nel momento in cui emetti una fattura, questa non viene registrata in contabilit&agrave fino a quando non la registri con 'Registra incasso fattura'.<br>In questo modo puoi decidere se regisrare le fatture nell'emissione o nel momento dell'effetivo incasso.";
$Lhelpdecimali = "I decimi vanno con il punto es.: 12.34";
$LhelpIva = "Inserisci solo il numero della percentuale";
$LhelpModPaga = "Es. bonifico, contanti...";
?>
