<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloprimanota = "Registro prima nota Cassa";
$Ltotali = "Totali";
$Lnota = "I campi contrassegnati con l'asterisco sono obbligatori";
$LStampaCancellaModifica = "Stampa | Cancella | Modifica";
$Lstampa = "Stampa Primanota";
$Lazzera = "Azzera Prima Nota";
$Lcancella = "Cancella";
$Linserisciid = "Inserisci il numero id da cancellare e premi cancella";
$Lmodifica = "Modifica";
$Linserisciidmodifica = "Inserisci in numero id e campo da modificare<br>Inserisci la modifica su Nuovo record e premi modifica";
$Lnumero = "Numero";
$Lcampo = "Campo";
$Ldata = "Data";
$Ldescrizione = "Descrizione";
$Lentratacassa = "Entrata Cassa";
$Luscitacassa = "Uscita Cassa";
$Lentratabanca = "Entrata Banca";
$Luscitabanca = "Uscita Banca";
$Lnuovorecord = "Nuovo record";
$Lnuovomovimento = "Nuovo movimento Prima nota";
$Lvocecontoec = "Voce Conto ec.*:";
$Lcausale = "Causale";
$Linserirecausale = "Inserire la causale";
$Loperazione = "Operazione*:";
$Linserirecausale = "Inserire la causale del movimento";
$Limporto = "Importo:";
$Lsuggdecimali = "Per i decimali si utilizza il punto es.: 123.45";
$Ltipodivoce = "Tipo di voce:";
$Ltipomovimento = "Tipo di movimento:";
$Lcassa = "Cassa";
$Lentrata = "Entrata";
$Luscita = "Uscita";
$Lbanca = "Banca";
$Lprimanota = "Prima Nota";
$Lguadperdita = "Guad/Perdita";
$Lhelpprimanota = "Nel momento in cui emetti una ricevuta o una fattura, queste vengono automaticamente registrate in prima nota.<br>da qui puoi registrare le uscite di cassa o di banca e altri tipi di entrate.";

?>
