<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2014-01-19

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloric = "Ricevuta/Quietanza";
$Lnotaric = "I campi in rosso sono obbligatori";
$Lstampa = "Stampa";
$Listrstampa = "Inserisci il numero della ricevuta e premi -Stampa-";
$Lnumero = "Numero";
$Lcancella = "Cancella";
$Listrcancella = "Inserisci il numero della ricevuta da cancellare e premi cancella";
$Lnumric = "Numero Ricevuta";
$Lvocecontoec = "Voce Conto ec.";
$Lcausale = "Causale";
$Listrcontoec = "Indica dove &egrave inserita la voce nel conto economico per poterla scalare";
$Lmodifica = "Modifica";
$Listrmodifica = "Inserisci il numero della ricevuta e campo da modificare<br>Inserisci la modifica su Nuovo record e premi modifica";
$Lcampo = "Campo";
$Lnome = "Nome";
$Ldata = "Data";
$Lmodalita = "Modalit&agrave ";
$Lsuggcausale = "Scegli la modalit&agrave, se libera compila il campo sottostante";
$Lpreimpostata = " Preimpostata ";
$Llibera = " Libera";
$Lprezzo = "Prezzo";
$Ldescrizione = "Descrizione";
$Ltesseramentocscadenza = "Tesseramento con avviso scadenza a 12 mesi";
$Ltesseramentonoscadenza = "Tesseramento senza avviso scadenza";
$Lnuovorecord = "Nuovo record";
$Listrnuovorecord = "Se modifichi un prezzo, Aggiorna il Conto Economico";
$Lnuova = "Nuova";
$Linserirecausale = "Inserire la causale";
$Lricevutoda = "<small>Ricevuto da</small>";
$Leuro = "Euro";
$Lstampcancmod = "Stampa | Cancella | Modifica";
$Linvia = "Invia";
$Lelencoricevute = "Elenco ricevute";
$Lhelpric = "Il numero progressivo della ricevuta &egrave automatico, mentre la data viene preimpostata, ma puoi modificarla.<br>Ricorda di inserire sempre correttamente la voce del conto economico per mantenere una contabilit&agrave esatta.";

?>
