<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Linvia = "Invia";
$Ltitolostatopatr = "Stato Patrimoniale";
$Lnota1 = "I campi contrassegnati con l'asterisco sono obbligatori";
$Lstampastatopat = "Stampa Stato Patrimoniale";
$Lazzerastatopat = "Azzera Stato Patrimoniale";
$Lcancella = "Cancella";
$Lnotacancella = "Inserisci il numero id da cancellare e premi cancella";
$Lnumero = "Numero";
$Lmodifica = "Modifica";
$Lnotamodifica = "Inserisci in numero id e campo da modificare<br>Inserisci la modifica su Nuovo record e premi modifica";
$Lcampo = "Campo";
$Ldescrizione = "Descrizione";
$Lvalore = "Valore";
$Lnuovorecord = "Nuovo record";
$Lnuovavoce = "Nuova voce Stato Patrimoniale";
$Loperazione = "Operazione";
$Linscausale = "Inserire la causale";
$Lnotavalore = "Evitare di inserire simboli come +,-* ecc. i decimali vanno con il punto es.: 123.45";
$Ltipovoce = "Tipo di voce";
$Lattivita = "Attivit&agrave";
$Lpassivita = "Passivit&agrave";
$Lid = "id";
$Limporto = "Importo";
$Ltotaleattivi = "Totale Attivi";
$Ltotalepassivi = "Totale Passivi";
$Lavanzogestione = "Avanzo di Gestione";
$Ltotpareggio = "Totale a pareggio";
$Lhelpatatopatr = "Sinx assegna automaticamente i valori di cassa e banca nello stato patrimoniale.<br>Gli altri valori patrimoniali dell'Associazione, si inseriscono agendo su 'modifica' e assegnando il campo 'valore' e l'id della voce di riferimento.<br>Sinx ricalcoler&agrave i totali.<br>E' sempre possibile cancellare, modificare ed aggiungere ulteriori voci del patrimonio.";

?>
