<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitololog = "Log del sistema";
$Lcanclog = "Azzera log di sistema";
$Lsugg1log = "Il file di log &egrave utile per avere uno storico del sistema, per&ograve pu&ograve arrivare ad avere dimensioni grandi;<br>quando si &egrave sicuri, &egrave possibile azzerare il file.";
$Lhelp1log = "Il tuo utente ha un livello ";
$Lhelp2log = "Area permessa solo all'utente ";

?>