<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//Menu
$Lassociazione = "Associazione";
$Lsito = " Sito Web";
$Ldatiassociazione = " Dati Associazione";
$Lmail="Web Mail";
$Lmailpec="Web Mail Pec";
$Lfacebook="Facebook";
$Linstagram="Instagram";
$Lyoutube="YouTube";
$Ltwitter="Twitter";
$LHomeBanking="Home Banking";
$Lanagrafica = "Anagrafica";
$Lfondatori = " Direttivo";
$Lassociati = " Associati";
$Limporta = " Importa da csv";
$Laltri = " Altri/Collaboratori";
$Lcerca = " Cerca";
$Lrubrica = " Rubrica";
$Llibrosoci = " Libro Soci";
$Lcontabilita = "Contabilit&agrave";
$Lprimanota = " Prima Nota";
$Lquietanza = " Quietanza";
$Lfattura = " Fattura";
$Lcontoec = " Conto Economico";
$Lstatopat = " Stato Patrimoniale";
$Lrendiconto = " Rendiconto";
$Lnuovoannosociale = " Nuovo Anno Sociale";
$Lgestione = "Gestione";
$Lmoduli = " Moduli";
$Lcalendario = " Calendario";
$Lutenti = " Utenti";
$Lfileseimmagini = " Files e Immagini";
$Llog = " Log di sistema";
$Lspecifiche = "Specifiche";
$Lfunzioniassociati = " Funzioni Associati";
$Ltipoassociati = " Tipologia Associati";
$Lmanuale = "Manuale";
$Luscita = "Uscita";
$Llicenza = "Licenza Gnu GpL/v3";
$Lblocconote = "Blocco Note";

?>
