<?php
/*======================================================================+
 File name   : Nannosoc.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitolotipoass = "Inserimento tipo associato";
$Lcanctipoass = "Cancella";
$Lsuggcanctipoass = "Inserisci il numero id da <b>cancellare</b> e premi cancella";
$Lmodtipoass = "Modifica";
$Lsuggmodtipoass = "Inserisci in numero id<br>Inserisci la <b>modifica</b> su Nuovo record e premi modifica";
$Lnuovorecordtipoass = "Nuovo record";
$Lnuovotipoass = "Nuovo";
$Lsociotipoass = " Socio";
$Lelencotipoass = "Elenco";
$Ltitoloelencotipoass = "Tipi di soci nel database";
$Ltipotipoass = "tipo";
$Lhelptipoass = "Le tipologie degli associati sono gi&agrave impostate di default, ma puoi sempre aggiungerne o modificare quelle esistenti";

?>