<?php
/*======================================================================+
 File name   : moduli.inc
 Begin       : 2013-12-29
 Last Update : 2013-12-29

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta

               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

$Ltitolomoduli = "Inserisci i dati richiesti";
$Lsugg1moduli = "Sotto le caselle puoi trovare eventuali suggerimenti";
$Lmodulo = "Offerta / preventivo";
$LSuggPreventivo = "Questa voce non è modificabile";
$Lverbale = "Descrizione preventivo";
$LSuggDescrizione = "Testo completo dell'offerta - Ricorda di aggiungere le eventuali condizioni (iva, pagamento ecc.)</br>Ricorda che per andare a capo bisogna utilizzare il tag html";
$Lassociato = "Richiedente offerta";
$Lnome = "Nome";
$Ldataoff = "Data offerta";
$Lsugg2moduli = "Per la compilazione del preventivo, è possibile utilizzare i tag html es.:";
$Lvacapo = "va a capo";
$Lgrassetto = "Grassetto";
$Lcorsivo = "Corsivo";
$Llineaorr = "Linea orizzontale";
$Lelenco = "elenco puntato";
$Loggetto = "Oggetto";
$Lpreventivilavori = "Preventivo";
$Lsugg3moduli = "Compila i campi richiesti per la realizzazione del preventivo o dell'offerta. Una volta pronta, potrai stamparla, salvarla o inviarla per email";
$Llivutente1 = "Il tuo utente ha un livello ";
$Llivutente2 = "Area permessa solo all'utente ";
$Llivutente3 = "Admin";
$LSalvaCopiaFiles = "Salva anche una copia nei files";

?>
