<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitolorendiconto = "Rendiconto economico";
$Lrendicontoanno = "Rendiconto economico annuale";
$Lnuovoschema = "Nuovo schema di bilancio e altri documenti";
$Ldescrrendiconto = "La L.266/91 (art.3 comma 3) stabilisce che nell'atto costitutivo o nello statuto delle Organizzazioni di
volontariato devono essere previsti:
<li>- l'obbligo di formazione del bilancio;</li>
<li>- le modalit&agrave di approvazione dello stesso da parte dell'Assemblea degli aderenti.</li>
<br>
La norma non indica schemi precostituiti ma si limita a richiedere che dal bilancio risultino i beni, i contributi o i lasciti ricevuti.<br>
Tale documento, oltre ad essere obbligatorio per legge, risponde all'esigenza di trasparenza e di pubblicit&agrave nei confronti di tutti i soggetti che vengono a vario titolo in contatto con l'organizzazione, &egrave il principale strumento per dimostrare l'attivit&agrave svolta ed &egrave necessario perche l'organizzazione possa mantenere la qualifica di Ente non commerciale e godere delle agevolazioni fiscali previste.
<br><br>
Il bilancio va approvato dall'Assemblea nei tempi previsti dallo Statuto e pertanto va necessariamente accompagnato da copia del verbale di approvazione da parte della Assemblea, datato e sottoscritto dal legale rappresentante.<br>
Il rendiconto economico andr&agrave accompagnato da una relazione o cd. rendicontazione sociale.<br>
Numerose previsioni normative, quali ad esempio, gli obblighi di rendicontazione dell'utilizzo dei fondi del cinque per mille, richiedono che il rendiconto economico sia affiancato e integrato con una rendicontazione sociale.<br>
Attraverso tale documento l'organizzazione potr&agrave fornire indicazioni utili al fine di:
<li>- Evidenziare i tratti essenziali del servizio 'istituzionale' svolto;</li>
<li>- Analizzare sommariamente la capacit&agrave di lavoro in rete sul territorio;</li>
<li>- Mostrare l'impegno per sostenere e valorizzare il patrimonio umano, quale risorsa prioritaria, coinvolto nell'organizzazione: volontari, dirigenti e sostenitori.</li>
<br>
Si ricorda anche l'obbligo di tenere separati rendiconti delle singole raccolte pubbliche di fondi, imposto dall'art. 8 del D.lgs 460/97, e ribadito dalla Circolare n. 59 del 31 ottobre 2007.<br> La somma dei risultati delle singole raccolte fondi, andr&agrave naturalmente a costituire la pi&ugrave ampia voce di bilancio 'raccolte fondi'.
<br><br>
Al bilancio dell'organizzazione di volontariato vanno, pertanto, sempre allegati i seguenti documenti:
<li>1. Verbale di approvazione del rendiconto da parte dell'Assemblea dei soci;</li>
<li>2. Relazione sociale;</li>
<li>3. Eventuali rendiconti e relazioni illustrative delle singole raccolte fondi effettuate;</li>
<li>4. Eventuale rendiconto della destinazione del cinque per mille ricevuto";
$Lhelprendiconto = "Sinx predispone la rendicontazione economica, scegli il tipo di rendicontazione a seconda se la tua associazione &egrave una aps (associazione di promozione sociale) o un odv (organizzazione di volontariato).";

?>