<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Ltitoloricerca = "Ricerca Associati";
$Lfondatori = " Direttivo";
$Lfunzione = "Funzione  ";
$Lnota1 = "Lasciando vuoto, si otterr&agrave la lista completa in ordine alfabetico";
$Lassociati = " Associati";
$Ltipo = "Tipo ";
$Lcontatti = " Contatti";
$Lricercaricevute = "Ricerca Ricevute Associati";
$Lnota2 = "Questa funzione esegue una ricerca all'interno delle ricevute emesse.<br>
Utile, per esempio, per visionare la lista dei tesserati, oppure di chi ha dato un contributo.<br>
E' possibile inserire pi&ugrave parole nella stessa ricerca inserendo il <b>carattere speciale % </b>tra di esse.<br>
La ricerca non &egrave case sensitive";
$Lcamporicerca = "Campo di ricerca:";
$Lricercanome = " nome |";
$Lricercadescrizione = " descrizione |";
$Lvalore = " valore |";
$Lricercadata = " data";
$Lricerca = "Ricerca *:";
$Lcerca = "Cerca";
$Ltitoloesempio = "Esempio uso carattere speciale %:";
$Lesempioricric = "<small><b>%descr% - </b>Ricerca tutto ci&ograve che comprende 'descr' e quello che c'&egrave prima e dopo</small><br>
<small><b>Rob% - </b>Ricerca tutte le parole che iniziano per Rob e quello che c'&egrave dopo</small><br>
<small><b>%2016 - </b>Ricerca tutte le date dell'anno 2016</small>";
$Lhelpricerca = "<hr><center><img src='./Immagini/suggerimento.png'><small><i>Nella ricerca per nome &egrave possibile ottenere la lista completa in ordine alfabetico lasciando libera la casella delle lettere di ricerca.<br>La ricerca ricevute &egrave utile per avere la lista dei tesserati o le ricevute emesse per un progetto o in un determinato periodo di tempo.
<hr></i></small></center>";
$Lsugg1utente = "Il tuo utente ha un livello ";
$Lsugg2utente = "Area permessa solo all'utente ";

?>
