<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lpresentazionebackup = "Gestione Backup dati";
$Lbackup = "Backup dei dati";
$Lcomandobackup = "Premi il pulsante per il salvataggio dei dati";
$Lripristino = "Ripristino dei dati";
$Listrripristino = "Sezione per il ripristino dei dati salvati in precedenza<br><b>Attenzione!!</b> &egrave possibile che per il ripristino dei dati ci vogliano alcuni istanti, attendere durante il ripristino senza interrompere";
$Lfilebackup = "File Backup:";
$Lhelpbackup = "<hr><img src='./Immagini/suggerimento.png'><small><i>E' sempre consigliabile fare un backup dei dati periodico.<br>Il file di backup verr&agrave salvato nel pc locale e non sul server
<hr></i></small>";
$Lutentelimitato = "<center>Il tuo utente ha un livello <b>$user</b> <br>Area permessa solo all'utente <b>Admin</b></center>";
$Linvia = "Invia";

?>
