<?php
/*======================================================================+
 File name   : ita.inc
 Begin       : 2013-08-04
 Last Update : 2013-08-27

 Description : italy language file

 Author: Sergio Capretta

 (c) Copyright:
               Sergio Capretta
             
               ITALY
               www.sinx.it
               info@sinx.it

Sinx for Association - Gestionale per Associazioni no-profit
    Copyright (C) 2011 by Sergio Capretta

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
=========================================================================+*/

//top
$Lidprovincia = "Id Provincia";
$LidRegione = "Id Regione";
$LProvincia = "Provincia";
$Lnome = "Nome ";
$Lmodifica = "Modifica";
$Lcancella = "Cancella";
$Laggiungi = "Aggiungi";
$Lsuggerimento = "<hr><img src='./Immagini/suggerimento.png'><br><small><i>Per qualsiasi operazione, devi specificare l'identificativo (Id) di Provincia e Regione, quindi decidi se modificare, cancellare o aggiungere e premi il pulsante Vai<br><b>Fai attenzione</b> che Regioni, Province e Comuni sono tabelle collegate tra di loro, cambiare un Id può significare la perdita dei dati<br><hr></i></small>";

?>
